### ISSUE TITLE
Display openstreet map on index page

### ISSUE THREAD

**Issue by Siliconlad** [automat-ed/portal#11]
Before we can display the location of the robots, we need to be able to display a map. This map should be customizable. In other words, we should be able to load custom maps to allow us to be able to load our simulation environments (also created using OpenStreetMaps). This is primarily to allow us to run the Portal while using the simulation for testing purposes.

There should also be consultation with the UI mockups from #4.

# Task
For this issue, the frontend should be able to load any map defined using the OpenStreetMap protocol in addition to the normal world map so we could run it in the real world if we wanted to.

**Comment by alkg** [comment]
When refactoring and sorting out building, read this: https://create-react-app.dev/docs/deployment

**Comment by Siliconlad** [comment]
The majority of the work was done in #16. There is still a problem with rendering custom maps, so keeping this open until that has been resolved. Moving to Demo 3.

**Comment by alkg** [comment]
**Custom Maps**

1. Generate a .OSM file 
2. Download a tool such as [Maperitive ](http://maperitive.net/)(Windows/Linux)
3. In Maperitive, File -> Open Map Source -> Select .OSM file
4. In the Map Sources box on the bottom right, select the "Web map" source and then click on the red 'X'. 
5. Go to Tools -> Generate Tiles. Maperitive will create a new folder called Tiles in the same directory as your Maperitive location
6. You can now put this Tiles folder inside the Public folder of the repo 
7. In the repo, go to src -> components -> Leaflet -> Leaflet.js 
8. Change the URL variable equal `/Tiles/{z}/{x}/{y}.png`

**Comment by alkg** [comment]
Custom maps from a given .OSM file now works following the above instructions.
